AWSTemplateFormatVersion: '2010-09-09'

Resources:
  SongsDatabase:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      DBInstanceIdentifier: all-cars-database
      PubliclyAccessible: true
      StorageType: gp2
      MasterUsername: root 
      MasterUserPassword: Welcome123 
      Engine: mysql
      EngineVersion: 8.0.28